### ISSUE TITLE
Improved name guessing

### ISSUE THREAD

**Issue by sindresorhus** [mabrasil/happy-valentines#2]
You could use my [fullname](https://github.com/sindresorhus/fullname) module for better name guessing ;)

**Comment by ythecombinator** [comment]
Oh, surely, @sindresorhus! Actually, looking for a smarter way to guess the name would be my very next step for the next release, so maybe [fullname](https://github.com/sindresorhus/fullname) is the best bet.

But as I implemented [here](https://github.com/mabrasil/happy-valentines/blob/master/src/index.ls#L19) it [breaks the build on older node versions](https://travis-ci.org/mabrasil/happy-valentines) - up to `0.12` - since the use of `const` in `strict` mode wasn't allowed up to them.

Maybe an issue with [fullname](https://github.com/sindresorhus/fullname)?

**Comment by sindresorhus** [comment]
Just require Node.js 4. No reason to support older Node.js versions for CLI tools, as CLI tools are installed on the user's computer and they can easily upgrade.

**Comment by ythecombinator** [comment]
Did it @sindresorhus! Released [v0.1.1](https://github.com/mabrasil/happy-valentines/tree/v0.1.1) :smile_cat:
